[package]
name = "deep_learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
ndarray = "0.15.4"
mnist = "0.5.0"
float-cmp = "0.9.0"
ndarray-rand = "0.14.0"
